

CREATE DATABASE IF NOT EXISTS jane;
USE jane;
CREATE TABLE Users(
UsersID int NOT NULL AUTO_INCREMENT,
#  Category,StudentID,StudentFirstName,StudentMiddleName,StudentLastName,BIRTHDATE,SchoolName
Category VARCHAR(255),
StudentID int,
StudentFirstName VARCHAR(255),
StudentMiddleName VARCHAR(255),
StudentLastName VARCHAR(255),
BIRTHDATE VARCHAR(50),
SchoolName VARCHAR(255),
PRIMARY KEY (UsersID)
);
CREATE TABLE janeAD(
SettingsID int NOT NULL AUTO_INCREMENT,
SettingsNickName VARCHAR(255) NOT NULL UNIQUE,
SettingsPassword VARCHAR(255) NOT NULL,
Name VARCHAR(255) NOT NULL,
AccountExpirationDate VARCHAR(255),
AccountNotDelegated VARCHAR(1),
AccountPassword VARCHAR(255),
AllowReversiblePasswordEncryption VARCHAR(1),
AuthType VARCHAR(255),
CannotChangePassword VARCHAR(1),
Certificates VARCHAR(255),
ChangePasswordAtLogon VARCHAR(1),
City VARCHAR(255),
Company VARCHAR(255),
Country VARCHAR(255),
Credential VARCHAR(255),
Department VARCHAR(255),
Description VARCHAR(255),
DisplayName VARCHAR(255),
Division VARCHAR(255),
EmailAddress VARCHAR(255),
EmployeeID VARCHAR(255),
EmployeeNumber VARCHAR(255),
Enabled VARCHAR(1),
Fax VARCHAR(255),
GivenName VARCHAR(255),
HomeDirectory VARCHAR(255),
HomeDrive VARCHAR(255),
HomePage VARCHAR(255),
HomePhone VARCHAR(255),
Initials VARCHAR(255),
Instance VARCHAR(255),
LogonWorkstations VARCHAR(255),
Manager VARCHAR(255),
MobilePhone VARCHAR(255),
Office VARCHAR(255),
OfficePhone VARCHAR(255),
Organization VARCHAR(255),
OtherAttributes VARCHAR(255),
OtherName VARCHAR(255),
PassThru VARCHAR(255),
PasswordNeverExpires VARCHAR(1),
PasswordNotRequired VARCHAR(1),
Path VARCHAR(255),
POBox VARCHAR(255),
PostalCode VARCHAR(255),
ProfilePath VARCHAR(255),
SamAccountName VARCHAR(255),
ScriptPath VARCHAR(255),
Server VARCHAR(255),
ServicePrincipalNames VARCHAR(255),
SmartcardLogonRequired VARCHAR(1),
State VARCHAR(255),
StreetAddress VARCHAR(255),
Surname VARCHAR(255),
Title VARCHAR(255),
TrustedForDelegation VARCHAR(1),
Type VARCHAR(255),
UserPrincipalName VARCHAR(255),
Confirm VARCHAR(255),
WhatIf VARCHAR(255),
PRIMARY KEY (SettingsID)
);

CREATE USER 'jane'@'localhost' IDENTIFIED BY 'janepassword';
GRANT ALL ON jane.* TO 'jane'@'localhost';

